defaults:
  - dataset: tinystory
  - model: transformer
  - optimizer: adamw
  - scheduler: cosine
  - _self_

training:
  steps: 10000
  batch_size: 128
  seed: 42
  device: "cuda:0"
  # context_length: 256
  grad_clip: 1.0
  eval_interval: 1000

logging:
  project: "CS336-XJ"
  save_dir: "outputs/" #"outputs/${model.name}/${optimizer.name}/"